### ISSUE TITLE
Errors regarding force field when using unknown residues

### ISSUE THREAD

**Issue by Ntr9999** [Becksteinlab/MDPOW#130]
I'm trying to run the package on quite an unusual molecule and I thought that my .itp file was correct, however, I am starting to doubt this.
When I run:
```
mdpow-equilibrium --solvent water runinput.yml
```
I was under the impression that mymolecule.itp was incorporated automatically by the package to the top of the topology file with #include.
Or am I required to update the force field files myself aswell? If so, are these the ones in the MDPOW directory, or in the gromacs installation in /opt/gromacs/? (Apologies if this is more of a GROMACS question- I thought I'd ask here first because I'm not sure if I would be required to edit files within the gromacs installation or the MDPOW directory)

I get error messages implying that the force field has not been adapted to the new "residue":
```
ERROR 1 [file diaz.itp, line 26]:
  No default Bond types

ERROR 2 [file diaz.itp, line 27]:
  No default Bond types

ERROR 3 [file diaz.itp, line 30]:
  No default Bond types

ERROR 4 [file diaz.itp, line 53]:
  No default Angle types

ERROR 5 [file diaz.itp, line 54]:
  No default Angle types

ERROR 6 [file diaz.itp, line 57]:
  No default Angle types

ERROR 7 [file diaz.itp, line 58]:
  No default Angle types

ERROR 8 [file diaz.itp, line 59]:
  No default Angle types

ERROR 9 [file diaz.itp, line 60]:
  No default Angle types

ERROR 10 [file diaz.itp, line 62]:
  No default Angle types

ERROR 11 [file diaz.itp, line 64]:
  No default Angle types

ERROR 12 [file diaz.itp, line 66]:
  No default Angle types

ERROR 13 [file diaz.itp, line 67]:
  No default Angle types

ERROR 14 [file diaz.itp, line 68]:
  No default Angle types

ERROR 15 [file diaz.itp, line 69]:
  No default Angle types

ERROR 16 [file diaz.itp, line 70]:
  No default Angle types

ERROR 17 [file diaz.itp, line 71]:
  No default Angle types

ERROR 18 [file diaz.itp, line 76]:
  No default Ryckaert-Bell. types

ERROR 19 [file diaz.itp, line 79]:
  No default Ryckaert-Bell. types

ERROR 20 [file diaz.itp, line 80]:
  No default Ryckaert-Bell. types

ERROR 21 [file diaz.itp, line 82]:
  No default Ryckaert-Bell. types

ERROR 22 [file diaz.itp, line 83]:
  No default Ryckaert-Bell. types
```

`grompp_qtot() failed. See warning and screen output for clues.`

I assume grumpp_qtot is failing because of these errors, or should I change my qtot to an integer, I didn't think this was actually essential.

Here is my .ipt and .yml file
my .ipt file:
```
[ moleculetype ]
; Name            nrexcl
DIA                 3

[ atoms ]
;   nr       type  resnr residue  atom   cgnr     charge       mass  typeB    chargeB      massB
     1   opls_135      1    DIA      C      1     -0.180   12.01100                             
     2   opls_906      1    DIA      C      2      0.060   12.01100                             
     3   opls_900      1    DIA      N      3     -0.900   14.00670                             
     4   opls_909      1    DIA      H      3      0.360    1.00800                             
     5   opls_909      1    DIA      H      3      0.360    1.00800                             
     6   opls_900      1    DIA      N      4     -0.900   14.00670                             
     7   opls_909      1    DIA      H      4      0.360    1.00800                             
     8   opls_909      1    DIA      H      4      0.360    1.00800                             
     9   opls_145      1    DIA      C      5     -0.115   12.01100                             
    10   opls_146      1    DIA      H      5      0.115    1.00800                             
    11   opls_154      1    DIA      O      5     -0.683   15.99940                             
    12   opls_155      1    DIA      H      5      0.418    1.00800                             
    13   opls_236      1    DIA      O      5     -0.500   15.99940                             

[ bonds ]
;  ai    aj funct
    1     2     1	;     C     C
    1     3     1	;     C     N
    1     4     1	;     C     H
    1     5     1	;     C     H
    2     6     1	;     C     N
    2     9     1	;     C     C
    2    10     1	;     C     H
    3     6     1	;     N     N
    3     8     1	;     N     H
    6     7     1	;     N     H
    9    11     1	;     C     O
    9    13     1	;     C     O
   11    12     1	;     O     H

[ pairs ]
;  ai    aj funct
    2     6     1	;     C     N
    2     8     1	;     C     H
    1     7     1	;     C     H
    1    11     1	;     C     O
    1    13     1	;     C     O
    1     7     1	;     N     H
    6    11     1	;     N     O
    6    13     1	;     N     O
    2    12     1	;     C     H

[ angles ]
;  ai    aj    ak funct
    2     1     3     1	;     C     C     N
    2     1     4     1	;     C     C     H
    2     1     5     1	;     C     C     H
    1     2     6     1	;     C     C     N
    1     2     9     1	;     C     C     C
    1     2    10     1	;     C     C     H
    3     1     4     1	;     N     C     H
    3     1     5     1	;     N     C     H
    1     3     6     1	;     N     C     N
    1     3     8     1	;     N     C     H
    4     1     5     1	;     H     C     H
    6     2     9     1	;     N     C     C
    6     2    10     1	;     N     C     H
    2     6     7     1	;     N     C     H
    9     2    10     1	;     C     C     H
    2     9    11     1	;     C     C     O
    2     9    13     1	;     C     C     O
    6     3     8     1	;     N     N     H
    3     6     7     1	;     N     N     H
   11     9    13     1	;     O     C     O
    9    11    12     1	;     O     C     H

[ dihedrals ]
;  ai    aj    ak    al funct
    2     1     3     6     3	;     C     C     N     N
    2     1     3     8     3	;     C     C     N     H
    1     2     6     7     3	;     C     C     N     H
    1     2     9    11     3	;     C     C     C     O
    1     2     9    13     3	;     C     C     C     O
    1     3     6     7     3	;     N     C     N     H
    6     2     9    11     3	;     N     C     C     O
    6     2     9    13     3	;     N     C     C     O
    2     9    11    12     3	;     C     C     O     H

[ dihedrals ]
;  aj    ak    ai    al funct
    1     6     3     8     1    improper_Z_N_X_Y	;     H     C     N     N
    2     7     6     3     1    improper_Z_N_X_Y	;     N     C     H     N
    2    13     9    11     1    improper_O_C_X_Y	;     O     C     O     C

```

My .yml file:
```yml
DEFAULT:
  qscripts: local.sh
FEP:
  maxwarn: 0
  mdp: bar_opls.mdp
  method: BAR
  qscript: local.sh
  runlocal: true
  runtime: 5000
FEP_schedule_Coulomb:
  couple_lambda0: vdw-q
  couple_lambda1: vdw
  description: dis-charging vdw+q --> vdw
  label: Coul
  lambdas: 0, 0.25, 0.5, 0.75, 1.0
  name: Coulomb
  sc_alpha: 0
  sc_power: 1
  sc_sigma: 0.3
FEP_schedule_VDW:
  couple_lambda0: vdw
  couple_lambda1: none
  description: decoupling vdw --> none
  label: VDW
  lambdas: 0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9,
    0.95, 1
  name: vdw
  sc_alpha: 0.5
  sc_power: 1
  sc_sigma: 0.3
MD_NPT:
  mdp: NPT_opls.mdp
  qscript: local.sh
  runlocal: true
  runtime: 50000
MD_relaxed:
  mdp: NPT_opls.mdp
  qscript: local.sh
  runlocal: true
  runtime: 5
energy_minimize:
  mdp: em_opls.mdp
mdrun:
  maxthreads: None
  nice: 19
  stepout: 1000
  verbose: true
setup:
  boxtype: dodecahedron
  distance: None
  forcefield: OPLS-AA
  gromacsoutput: false
  itp: "/Users/mark/Desktop/diaz/diaz.itp"
  maxwarn: 0
  molecule: dia
  name: diaz
  prm: None
  solventmodel: tip4p
  structure: "/Users/mark/Desktop/diaz/diaz.pdb"
```
 Another quick question, what is the prm parameter in the setup section of the yml file (it is not present in the benzene tutorial example)?

Thank you very much for any assistance, it is greatly appreciated.
