### ISSUE TITLE
choosing different water models

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#38]
We want to be able to select the **water model** as a configuration parameter. For example:

* [x] TIP4P (default for OPLS-AA, what we currently use)
* [ ] SPC
* [ ] SPC/E
* [ ] TIP4Pew (TIP4P for Ewald summation (like PME)) – not sure if available in Gromacs
* [ ] TIP3P (simple)
* [ ] TIP3P (CHARMM version)

**Comment by orbeckst** [comment]
@iorga is also interested in this feature.

**Comment by orbeckst** [comment]
@iorga : if you use the latest development branch
```
git pull
git checkout -b develop origin/develop
cd mdpow
pip install --upgrade --user .
```
then you can set the configuration variable `setup.watermodel` to any of the water models currently available in Gromacs with OPLS-AA. E.g., with TIP3P
```yml
setup:
    name: benzene_tip3p
         # common, descriptive name, e.g. benzene
    molecule: BNZ
         # Gromacs [ molecule ] identifier from the itp file (typically a 3-letter code)
    watermodel: tip3p
         # water model available in Gromacs (OPLS-AA):
         # tip4p, tip5p, tip3p, spc, spce     
    itp: benzene/benzene.itp
         # Gromacs itp file name 
    structure: benzene/benzene.pdb
         # coordinate file name (pdb, gro, ... anything that Gromacs can read)
    maxwarn: 0
         # maximum number of warnings tolerated by grompp during setup
    gromacsoutput: True
         # True: print output from Gromacs command to screen (useful for debugging)
         # False: only show the MDPOW messages
```

If you don't have the `setup.watermodel` variable then it will simply default to `tip4p` (as before).
