### ISSUE TITLE
variable expansion in config file not working anymore

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#42]
It used to be possible to define a variable in the `DEFAULT` section and then use the variable in other sections (the ini parser was able to do it) but with the YAML format this does not work anymore. Thus, the following from the **template runinput.yml** is not working anymore:

``` yml
DEFAULT:
    qscripts: local.sh


MD_NPT:
    qscript: (qscripts)s
         # queuing system scripts to produce
```
