### ISSUE TITLE
change config parser to use yml lists instead of getlist()

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#9]
One advantage of using yml is that it has rich data structures. We should make use of this and change the runinput config syntax to use
- deeper nestings (dict-like)
- lists

This will also make it easier to implement #2.

However, it will _break the input file format_ so we might want to wait with this until current projects are done...
### Lists

``` yaml
lambdas: 0.0, 0.25, 0.5, 0.75, 1.0
```

to using [YAML lists](http://pyyaml.org/wiki/PyYAMLDocumentation#Blocksequences)

``` yaml
lambdas: [0.0, 0.25, 0.5, 0.75, 1.0]
```

or 

``` yaml
lambdas: 
  - 0.0
  - 0.25
  - 0.5
  - 0.75
  - 1.0
```
### Deeper nesting

Similarly, we should use deeper nestings such as

``` yaml
FEP:
   maxwarn: 1
   mdp: "bar_opls.mdp"
   method: "BAR"
   qscript: "wsq_4_MDPOW_array_default_466.sge"
   runlocal: False
   runtime: 5000
   schedule:
     Coulomb:
           couple_lambda0: "vdw-q"
           couple_lambda1: "vdw"
           description: "dis-charging vdw+q --> vdw"
           label: "Coul"
           lambdas: [0.0, 0.25, 0.5, 0.75, 1.0]
           name: Coulomb
           sc_alpha: 0
           sc_power: 1
           sc_sigma: 0.3
     VDW:
           couple_lambda0: "vdw"
           couple_lambda1: "none"
           description: "decoupling vdw --> none"
           label: "VDW"
           lambdas: [0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1]
           name: vdw
           sc_alpha: 0.5
           sc_power: 1.0
           sc_sigma: 0.3
```

**Comment by orbeckst** [comment]
Similarly, we should use deeper nestings such as

```yaml
FEP:
   maxwarn: 1
   mdp: "bar_opls.mdp"
   method: "BAR"
   qscript: "wsq_4_MDPOW_array_default_466.sge"
   runlocal: False
   runtime: 5000
   schedule:
     Coulomb:
           couple_lambda0: "vdw-q"
           couple_lambda1: "vdw"
           description: "dis-charging vdw+q --> vdw"
           label: "Coul"
           lambdas: [0.0, 0.25, 0.5, 0.75, 1.0]
           name: Coulomb
           sc_alpha: 0
           sc_power: 1
           sc_sigma: 0.3
     VDW:
           couple_lambda0: "vdw"
           couple_lambda1: "none"
           description: "decoupling vdw --> none"
           label: "VDW"
           lambdas: [0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1]
           name: vdw
           sc_alpha: 0.5
           sc_power: 1.0
           sc_sigma: 0.3
```
